export const toolbarOptions = [
    { header: [1, 2, 3, 4, 5, 6, false] },
    { font: [] },
    "bold",
    "italic",
    "underline",
    "strike",
    "blockquote",
    "link",
    "image",
    { list: "ordered" },
    { list: "bullet" },
    { color: [] },
    { align: [] },
    "clean",
];
